spring:
  cache:
    type: redis
    redis:
      time-to-live: PT60M
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:63792}
  application:
    name: JobFinder
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_AUTH_SOURCE}
      auto-index-creation: true

scheduler:
  enabled: true

offer:
  http:
    client:
      uri: ${OFFER_CLIENT_URI}
      port: ${OFFER_CLIENT_PORT:5057}
      connectionTimeout: 4000
      readTimeout: 4000
  fetcher:
    scheduler:
      fixedDelay: PT3H  # 10800000 = 3 hours in milliseconds

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: job-offers-backend

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always